import Head from "next/head";
import Image from "next/image";
import Features_about from "../components/Features_about";
import Header from "../components/Header";
import Team from "../components/Team";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>About us - W.E. Lyons Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          title="About us"
          description="W.E. Lyons Construction is a family owned business."
          image="https://images.unsplash.com/photo-1528686086515-695fb0f1ee0c?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1506&q=80"
        />
        <Features_about />
        <Team />
      </main>
    </div>
  );
}
