import Head from "next/head";
import Image from "next/image";
import Features_about from "../components/Features_about";
import Header from "../components/Header";
import Team from "../components/Team";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>About us - W.E. Lyons Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          title="About us"
          description="W.E. Lyons Construction is a family owned business."
        />
        <Features_about />
        <Team />
      </main>
    </div>
  );
}
