import Head from "next/head";
import Image from "next/image";
import CTA from "../components/CTA";

import Header from "../components/Header";
import Joblist from "../components/Joblist";

export default function careers() {
  return (
    <div>
      <Head>
        <title>Contact Us Now - W.E. Lyons Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          title="Careers"
          description="Are you looking for exciting opportunities. You are at the right place "
          image="https://images.unsplash.com/photo-1557425529-b1ae9c141e7d?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80"
        />

        <Joblist />
      </main>
    </div>
  );
}
