import Head from "next/head";
import Image from "next/image";
import ContactForm from "../components/ContactForm";
import Header from "../components/Header";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact Us Now - W.E. Lyons Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          title="Contact us"
          description="Please don't hesitate to contact us."
        />
        <ContactForm />
      </main>
    </div>
  );
}
