import Head from "next/head";
import Image from "next/image";
import ContactForm from "../components/ContactForm";
import Header from "../components/Header";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Contact Us Now - W.E. Lyons Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header
          title="Contact us"
          description="Please don't hesitate to contact us."
          image="https://images.unsplash.com/photo-1596524430615-b46475ddff6e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1050&q=80"
        />
        <ContactForm />
      </main>
    </div>
  );
}
