import Head from "next/head";
import Image from "next/image";
import JobDescription from "../components/JobDescription";

export default function jobDescription() {
  return (
    <div>
      <Head>
        <title>Careers - Job Description</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <JobDescription />
      </main>
    </div>
  );
}
