import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home - W.E. Lyons Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Projects />
      </main>
    </div>
  );
}
